/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author nere1
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NuevoEvento = new javax.swing.JButton();
        PasarUnDia = new javax.swing.JButton();
        PasraDiezDias = new javax.swing.JButton();
        VerResumen = new javax.swing.JButton();
        CalentamientoGlobal = new javax.swing.JButton();
        EnfriamientoGlobal = new javax.swing.JButton();
        InvasionZombie = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ImgDia = new javax.swing.JLabel();
        ImgHumano = new javax.swing.JLabel();
        ImgVampiro = new javax.swing.JLabel();
        ImgTemperatura = new javax.swing.JLabel();
        ImgZombie = new javax.swing.JLabel();
        ImgCazaVampiro = new javax.swing.JLabel();
        nDia = new javax.swing.JLabel();
        temperatura = new javax.swing.JLabel();
        nCazavampiros = new javax.swing.JLabel();
        nVampiros = new javax.swing.JLabel();
        nZombies = new javax.swing.JLabel();
        nHumanos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NuevoEvento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NuevoEvento.setText("NUEVO ENTORNO");
        NuevoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoEventoActionPerformed(evt);
            }
        });

        PasarUnDia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PasarUnDia.setText("PASAR UN DIA");
        PasarUnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasarUnDiaActionPerformed(evt);
            }
        });

        PasraDiezDias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PasraDiezDias.setText("PASAR 10 DIAS");

        VerResumen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VerResumen.setText("VER RESUMEN");
        VerResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerResumenActionPerformed(evt);
            }
        });

        CalentamientoGlobal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CalentamientoGlobal.setText("CALENTAMIENTO GLOBAL");

        EnfriamientoGlobal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EnfriamientoGlobal.setText("ENFRIAMIENTO GLOBAL");
        EnfriamientoGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnfriamientoGlobalActionPerformed(evt);
            }
        });

        InvasionZombie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InvasionZombie.setText("INVASION DE ZOMBIES");

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 0, 24)); // NOI18N
        jLabel1.setText("SIMULADOR INVASIÓN");

        ImgDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/calendario.png"))); // NOI18N

        ImgHumano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/humano.png"))); // NOI18N

        ImgVampiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Vampiro.png"))); // NOI18N

        ImgTemperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/teperatura.png"))); // NOI18N

        ImgZombie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/zombie.png"))); // NOI18N

        ImgCazaVampiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/cazavampiro.png"))); // NOI18N

        nDia.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nDia.setText("0");

        temperatura.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        temperatura.setText("0");

        nCazavampiros.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nCazavampiros.setText("0");

        nVampiros.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nVampiros.setText("0");

        nZombies.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nZombies.setText("0");

        nHumanos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nHumanos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(1042, 1042, 1042)
                        .addComponent(ImgZombie))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(ImgHumano))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(ImgDia)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(374, 374, 374)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nDia)
                                    .addComponent(nHumanos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(ImgTemperatura)
                                                .addGap(103, 103, 103))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(ImgCazaVampiro)
                                                .addGap(62, 62, 62)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(temperatura)
                                                .addGap(83, 83, 83)
                                                .addComponent(ImgVampiro))
                                            .addComponent(nCazavampiros)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(PasraDiezDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CalentamientoGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(VerResumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(148, 148, 148)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(InvasionZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addComponent(PasarUnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnfriamientoGlobal)
                            .addComponent(NuevoEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(805, 805, 805)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nVampiros)
                    .addComponent(nZombies))
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(404, 404, 404))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ImgDia)
                                    .addComponent(ImgTemperatura)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(temperatura)
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(ImgHumano))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nCazavampiros)
                                .addGap(134, 134, 134))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImgVampiro, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(nDia))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(nVampiros)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImgZombie)
                            .addComponent(ImgCazaVampiro)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nZombies)
                                .addGap(127, 127, 127))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nHumanos)
                                .addGap(113, 113, 113)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasraDiezDias)
                    .addComponent(NuevoEvento)
                    .addComponent(PasarUnDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VerResumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnfriamientoGlobal)
                    .addComponent(CalentamientoGlobal)
                    .addComponent(InvasionZombie))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoEventoActionPerformed
        
    }//GEN-LAST:event_NuevoEventoActionPerformed

    private void PasarUnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasarUnDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasarUnDiaActionPerformed

    private void VerResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerResumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerResumenActionPerformed

    private void EnfriamientoGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnfriamientoGlobalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnfriamientoGlobalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalentamientoGlobal;
    private javax.swing.JButton EnfriamientoGlobal;
    private javax.swing.JLabel ImgCazaVampiro;
    private javax.swing.JLabel ImgDia;
    private javax.swing.JLabel ImgHumano;
    private javax.swing.JLabel ImgTemperatura;
    private javax.swing.JLabel ImgVampiro;
    private javax.swing.JLabel ImgZombie;
    private javax.swing.JButton InvasionZombie;
    private javax.swing.JButton NuevoEvento;
    private javax.swing.JButton PasarUnDia;
    private javax.swing.JButton PasraDiezDias;
    private javax.swing.JButton VerResumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nCazavampiros;
    private javax.swing.JLabel nDia;
    private javax.swing.JLabel nHumanos;
    private javax.swing.JLabel nVampiros;
    private javax.swing.JLabel nZombies;
    private javax.swing.JLabel temperatura;
    // End of variables declaration//GEN-END:variables
}
